# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([{ first_name: "Lucy", last_name: "Stone", email: "lstone@gmail.com", password: "password"}, { first_name: "Lucretia", last_name: "Mott", email: "bhastingtest@thinx.com", password: "password"}, {first_name: "Coco", last_name: "Chanel", email: "testing", password: "testing"}, { first_name: "Susan", last_name: "Anthony", email: "sueb@gmail.com", password: "password"}, { first_name: "Natalie", last_name: "Smith", email: "nsmith@gmail.com", password: "password"}, { first_name: "Elizabeth", last_name: "Cady-Stanton", email: "cadygal@gmail.com", password: "password"},{ first_name: "Jane", last_name: "Addams", email: "addamsfamily@gmail.com", password: "password"}])

posts = Post.create([{user_id: 2,title: "Thinx Panties", content: "Get them! It will be an insane upgrade on your old period panties. Size up if you need to support your booty. Be mindful of your personal flow, but I’ll definitely be wearing them tampon-less. I wore the underwear ALL DAY and did not have a leak. I did not feel wet. In periods past, I would have gone through the work day using at least two tampons, maybe three. Straight up? I was impressed.  I have confidence that they can hold up under pressure. So go forth, my fellow women. Bleed free, bleed proud.", img_url: "http://static.stuff.co.nz/files/thinxad"},{user_id: 1, title: "Spring App", content: "Spring is a feed, similar in look and feel to Instagram’s feed. Users follow brands that they like, and brands post images of product that’s for sale. (You can shop directly from the image.) Spring dutifully works with each brand to figure out how many times a day it makes sense to post, dependent on the amount of inventory the brand keeps. Many of the upstart designers I’ve spoken to find this part challenging. They don’t hold much inventory themselves, and they also don’t make as many styles each season. Which means their feeds can become quite repetitive. A few of the startup designers with whom I spoke said that the time spent shooting images for Spring hasn’t been worth it.", img_url: "http://1u88jj3r4db2x4txp44yqfj1.wpengine.netdna-cdn.com/wp-content/uploads/2014/08/spring-app-1.jpg"},
  {user_id: 4, title: "Alexa Chung's Book", content: "If you call your pop-culture fashion book It, then presumably you believe that you have It. In fairness, one thing that can't be disputed is that global trendsetter Alexa Chung is a British 21st-century It girl, but, without meaning to be pedantic, what It is it? Now based in New York, Chung, a former model, of part-Chinese descent, is a television presenter who's won the British Style award three times and had a Mulberry bag named after her. It could have done with more of this – more of the real Alexa. As it is, you find yourself thinking – what is this? A pop-art take on a memoir, a fashionista coffee-table book, or just a bit of fun – a brazen cash-in by an enterprising young style icon?", img_url: "http://www.avogueintention.com/wp-content/uploads/2014/11/alexachung.jpg"},
  {user_id: 3, title: "Balm DotCom", content: "Let's talk about the pricing for a moment. I think that both products are priced fairly, but I think the moisturizer is priced more fairly than the salve. Why? Well even drugstore moisturizers can cost from between $20 and $40 these days, and oftentimes you may pay around $25 for 1.0 oz. This Glossier moisturizer contains 1.7 oz. for $25. Totally in line with drugstore pricing. As for the salve, well if you were only going to use this on your lips, this tube would last you forever, making the $12 price tag a bit easier to justify. But since this product is designed as an all-in-one salve for cuticles, rough patches, scrapes, chapped lips, etc., I think it's a bit pricey considering that it's $12 for 0.68 oz. For comparison, other popular petroleum-based all-in-one salves like Smith's Rosebud Salve retail for $6 (0.8 oz.), while Lucas Pawpaw retails for around $9 (0.9 oz.). But I'll get into whether I feel the price of Glossier is justified (for me at least), in a moment.", img_url: "http://maniacmagazine.com/wp-content/uploads/2016/05/glossier-balm-dotcom.maniac-magazine.jpg"},


 {user_id: 3, title: "Drake Song", content: "What can I say, he's a legend.", img_url: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Drake_-_Hotline_Bling.png"},])
